export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const GET_RELATED_SKILLS = "GET_RELATED_SKILLS";
export const GET_RELATED_JOBS = "GET_RELATED_JOBS";
export const GET_SKILL_DETAILS = "GET_SKILL_DETAILS";
export const GET_SKILL_RELATED_SKILLS = "GET_SKILL_RELATED_SKILLS";
export const GET_RECOMMENDED_JOBS = "GET_RECOMMENDED_JOBS";
export const GET_SKILL_DESCRIPTION = "GET_SKILL_DESCRIPTION";
